services:
  hifiberry-dsp:
    build:
      context: .
      dockerfile: Dockerfile
    image: dobrikov91/hifiberry-dsp:v1.2
    ports:
      - "8089:8089"
    restart: unless-stopped
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
      - /sys:/sys
      - /dev:/dev
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      INSTALL_PROFILE_ON_FIRST_RUN: "true"
      SERVER_OPTIONS: "--alsa --lgsoundsync"
      ENABLE_SPDIF: "true"
